/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9p2_ricardoquiroz_rigobertobarahona;

/**
 *
 * @author rjqer
 */
public class Lab9P2_Main extends javax.swing.JFrame {

    /**
     * Creates new form Lab92_Main
     */
    public Lab9P2_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JP_juego = new javax.swing.JPanel();
        CB_juego = new javax.swing.JComboBox<>();
        JB_generar = new javax.swing.JButton();
        JB_ejecutar = new javax.swing.JButton();
        JP_Idioma = new javax.swing.JPanel();
        JP_correos = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI_abrirarchivo = new javax.swing.JMenuItem();
        JM_recientes = new javax.swing.JMenu();
        MI_limpiar = new javax.swing.JMenuItem();
        MI_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CB_juego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Modificar", "Seleccionar", "Eliminar", " " }));

        JB_generar.setText("Generar");

        JB_ejecutar.setText("Ejecutar");

        javax.swing.GroupLayout JP_juegoLayout = new javax.swing.GroupLayout(JP_juego);
        JP_juego.setLayout(JP_juegoLayout);
        JP_juegoLayout.setHorizontalGroup(
            JP_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_juegoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(JP_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CB_juego, 0, 140, Short.MAX_VALUE)
                    .addComponent(JB_generar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_ejecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(501, Short.MAX_VALUE))
        );
        JP_juegoLayout.setVerticalGroup(
            JP_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_juegoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CB_juego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_generar)
                .addGap(18, 18, 18)
                .addComponent(JB_ejecutar)
                .addContainerGap(500, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Juego", JP_juego);

        javax.swing.GroupLayout JP_IdiomaLayout = new javax.swing.GroupLayout(JP_Idioma);
        JP_Idioma.setLayout(JP_IdiomaLayout);
        JP_IdiomaLayout.setHorizontalGroup(
            JP_IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        JP_IdiomaLayout.setVerticalGroup(
            JP_IdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Idioma", JP_Idioma);

        javax.swing.GroupLayout JP_correosLayout = new javax.swing.GroupLayout(JP_correos);
        JP_correos.setLayout(JP_correosLayout);
        JP_correosLayout.setHorizontalGroup(
            JP_correosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        JP_correosLayout.setVerticalGroup(
            JP_correosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Correos", JP_correos);

        jMenu1.setText("Archivo");

        MI_abrirarchivo.setText("Abrir Archivo");
        jMenu1.add(MI_abrirarchivo);

        JM_recientes.setText("Archivos Recientes");
        jMenu1.add(JM_recientes);

        MI_limpiar.setText("Limpiar");
        jMenu1.add(MI_limpiar);

        MI_salir.setText("Salir");
        jMenu1.add(MI_salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab9P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab9P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab9P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab9P2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab9P2_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_juego;
    private javax.swing.JButton JB_ejecutar;
    private javax.swing.JButton JB_generar;
    private javax.swing.JMenu JM_recientes;
    private javax.swing.JPanel JP_Idioma;
    private javax.swing.JPanel JP_correos;
    private javax.swing.JPanel JP_juego;
    private javax.swing.JMenuItem MI_abrirarchivo;
    private javax.swing.JMenuItem MI_limpiar;
    private javax.swing.JMenuItem MI_salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
